version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: babel-jest
    versions:
    - 26.6.3
  - dependency-name: "@types/jest"
    versions:
    - 26.0.19
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: typescript
    versions:
    - 3.9.7
