language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
before_script: 
  - echo 'Starting build... 🚀'
  - npm run build
script:
  - "npm run test:coveralls"
after_success: echo 'Build succeeded! 💪'
after_failure: echo 'Build failed... 😢'