language: node_js
node_js:
  - "11.10.1"
cache:
  directories:
    - node_modules
before_script: echo 'Starting build... 🚀'
script: npm run build
after_success: echo 'Build succeeded! 💪'
after_failure: echo 'Build failed... 😢'